//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackerRank_CSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HackerRank_CSharp.Properties.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30_Days_of_Code.
        /// </summary>
        internal static string _30DaysOfCode {
            get {
                return ResourceManager.GetString("30DaysOfCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_AppleOrange.txt.
        /// </summary>
        internal static string AppleOrange {
            get {
                return ResourceManager.GetString("AppleOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_ArraySum.txt.
        /// </summary>
        internal static string ArraySum {
            get {
                return ResourceManager.GetString("ArraySum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_BetweenTwoSets.txt.
        /// </summary>
        internal static string BetweenTwoSets {
            get {
                return ResourceManager.GetString("BetweenTwoSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_BirthdayCandles.txt.
        /// </summary>
        internal static string BirthdayCandles {
            get {
                return ResourceManager.GetString("BirthdayCandles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenges_Easy.
        /// </summary>
        internal static string Challenges_Easy {
            get {
                return ResourceManager.GetString("Challenges_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_CompareTriplets.txt.
        /// </summary>
        internal static string CompareTriplets {
            get {
                return ResourceManager.GetString("CompareTriplets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_Day02.txt.
        /// </summary>
        internal static string Day02 {
            get {
                return ResourceManager.GetString("Day02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_Day05.txt.
        /// </summary>
        internal static string Day05 {
            get {
                return ResourceManager.GetString("Day05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_Day06.txt.
        /// </summary>
        internal static string Day06 {
            get {
                return ResourceManager.GetString("Day06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_Day07.txt.
        /// </summary>
        internal static string Day07 {
            get {
                return ResourceManager.GetString("Day07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_Day08.txt.
        /// </summary>
        internal static string Day08 {
            get {
                return ResourceManager.GetString("Day08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_Day09.txt.
        /// </summary>
        internal static string Day09 {
            get {
                return ResourceManager.GetString("Day09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_Day10.txt.
        /// </summary>
        internal static string Day10 {
            get {
                return ResourceManager.GetString("Day10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_Day11.txt.
        /// </summary>
        internal static string Day11 {
            get {
                return ResourceManager.GetString("Day11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_Day12.txt.
        /// </summary>
        internal static string Day12 {
            get {
                return ResourceManager.GetString("Day12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_Day15.txt.
        /// </summary>
        internal static string Day15 {
            get {
                return ResourceManager.GetString("Day15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_Day18.txt.
        /// </summary>
        internal static string Day18 {
            get {
                return ResourceManager.GetString("Day18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_Day20.txt.
        /// </summary>
        internal static string Day20 {
            get {
                return ResourceManager.GetString("Day20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_Day22.txt.
        /// </summary>
        internal static string Day22 {
            get {
                return ResourceManager.GetString("Day22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_Day23.txt.
        /// </summary>
        internal static string Day23 {
            get {
                return ResourceManager.GetString("Day23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_Day24.txt.
        /// </summary>
        internal static string Day24 {
            get {
                return ResourceManager.GetString("Day24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_Day25.txt.
        /// </summary>
        internal static string Day25 {
            get {
                return ResourceManager.GetString("Day25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_Day26.txt.
        /// </summary>
        internal static string Day26 {
            get {
                return ResourceManager.GetString("Day26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_Day28.txt.
        /// </summary>
        internal static string Day28 {
            get {
                return ResourceManager.GetString("Day28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_Day29.txt.
        /// </summary>
        internal static string Day29 {
            get {
                return ResourceManager.GetString("Day29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_DiagonalDifference.txt.
        /// </summary>
        internal static string DiagonalDifference {
            get {
                return ResourceManager.GetString("DiagonalDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_GradeStudents.txt.
        /// </summary>
        internal static string GradeStudents {
            get {
                return ResourceManager.GetString("GradeStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_MinMaxSum.txt.
        /// </summary>
        internal static string MinMaxSum {
            get {
                return ResourceManager.GetString("MinMaxSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_NumberLineJumps.txt.
        /// </summary>
        internal static string NumberLineJumps {
            get {
                return ResourceManager.GetString("NumberLineJumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestFile_PlusMinus.txt.
        /// </summary>
        internal static string PlusMinus {
            get {
                return ResourceManager.GetString("PlusMinus", resourceCulture);
            }
        }
    }
}
